# This file was generated by GoReleaser. DO NOT EDIT.
cask "sonda" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "8f79aacc1df45d36a3336f7deb666173707337b8339b06f12de50b1a939c73c4"
      url "https://github.com/NicolasCondezaR/sonda/releases/download/v#{version}/sonda_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "92ddc5e72133f189b0176f1748a6bfa061477a27043eef7a20336d590702c975"
      url "https://github.com/NicolasCondezaR/sonda/releases/download/v#{version}/sonda_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "92662489a018bd1772c7172270880fe3a9a93a0e57d9f1f1eec3a0f6eeab9481"
      url "https://github.com/NicolasCondezaR/sonda/releases/download/v#{version}/sonda_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c6fcb42a655697c5d55a1b76b07e5a49e567c2a193d41e9a1ae06148bd859e51"
      url "https://github.com/NicolasCondezaR/sonda/releases/download/v#{version}/sonda_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sonda"
  desc "Proxy depurador de tráfico de desarrollo: HTTP y gRPC, con protobuf decodificado y los trailers preservados"
  homepage "https://github.com/NicolasCondezaR/sonda"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sonda"
  binary "sonda-tui"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sonda"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sonda-tui"]
    end
  end

  # No zap stanza required

end
