# This file was generated by GoReleaser. DO NOT EDIT.
cask "sonda" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "329028b151c22ed9f9197d6f4f7d203482baf4a9375a71e696f18f4c2ff81703"
      url "https://github.com/NicolasCondezaR/sonda/releases/download/v#{version}/sonda_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d40666a28545670348b4ead436bc9dd4ca5fef8882f8a02a48c496ac31aca674"
      url "https://github.com/NicolasCondezaR/sonda/releases/download/v#{version}/sonda_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "493185b5246b478ac049f02c6ee4684ae3c2b970398201fae3c58f62b40415f3"
      url "https://github.com/NicolasCondezaR/sonda/releases/download/v#{version}/sonda_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "39054afd455494b1c6e3b58ecc7f4c2c927b10a9f35ad9f1df7a6566fa2c657c"
      url "https://github.com/NicolasCondezaR/sonda/releases/download/v#{version}/sonda_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sonda"
  desc "Proxy depurador de tráfico de desarrollo: HTTP y gRPC, con protobuf decodificado y los trailers preservados"
  homepage "https://github.com/NicolasCondezaR/sonda"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sonda"
  binary "sonda-tui"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sonda"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sonda-tui"]
    end
  end

  # No zap stanza required

end
