# This file was generated by GoReleaser. DO NOT EDIT.
cask "sonda" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "25b02ad215e20a15c77c2c910f6bcd61c53caed229fe9984617619270c268435"
      url "https://github.com/NicolasCondezaR/sonda/releases/download/v#{version}/sonda_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "79043479d284954d31644f2cb767998d4eb5135bdd7c8932687114edf691e34d"
      url "https://github.com/NicolasCondezaR/sonda/releases/download/v#{version}/sonda_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "933f39bec5a72b018aef8cf45abf079d008073f1cff75689627de3d7e6563ece"
      url "https://github.com/NicolasCondezaR/sonda/releases/download/v#{version}/sonda_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "33e7bf425ba4cd47753e3f00737be21e29ccaa87bc1accfcfd988096d91979e4"
      url "https://github.com/NicolasCondezaR/sonda/releases/download/v#{version}/sonda_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sonda"
  desc "Proxy depurador de tráfico de desarrollo: HTTP y gRPC, con protobuf decodificado y los trailers preservados"
  homepage "https://github.com/NicolasCondezaR/sonda"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sonda"
  binary "sonda-tui"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sonda"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sonda-tui"]
    end
  end

  # No zap stanza required

end
